---
name: Scan Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  scan-container:
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@47c841da8336306cb0fc8c6af588ac4d2ffeabd7 # v1.3.0
    with:
      runtime: python
