---
name: Test Container

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  test-container:
    permissions:
      contents: read
      pull-requests: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-test-container.yml@5d51938d791ceab8be0f0409b41a1de2dbb265bb # v1.3.2
